version: '3.8'

services:
  elite-ai-api:
    build:
      context: .
      dockerfile: src/EliteAI.API/Dockerfile
    image: elite-ai-api:local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - RABBITMQ_URL=amqp://elite_ai:xke.FMF6gfc9ung3eqm@rabbitmq:5672
      - RABBITMQ_PASSWORD=xke.FMF6gfc9ung3eqm
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
    networks:
      - elite-ai-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=elite_ai
      - RABBITMQ_DEFAULT_PASS=xke.FMF6gfc9ung3eqm
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    networks:
      - elite-ai-network

networks:
  elite-ai-network:
    driver: bridge 