version: '3.8'

services:
  elite-ai-api:
    build:
      context: .
      dockerfile: src/EliteAI.API/Dockerfile
    image: elite-ai-api:local
    volumes:
      - ./src/EliteAI.API/.env:/app/.env
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5000:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - elite-ai-network

  workout-generator:
    build:
      context: .
      dockerfile: src/EliteAI.WorkoutGenerator/Dockerfile
    image: elite-ai-workout-generator:local
    volumes:
      - ./src/EliteAI.WorkoutGenerator/.env:/app/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - elite-ai-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=elite_ai
      - RABBITMQ_DEFAULT_PASS=elite_ai_password
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - elite-ai-network

networks:
  elite-ai-network:
    driver: bridge 